### Numpy - stands for `Numerical Python`
- Is one of the most important python libraries for data science, machine learning, scientic computing and numerical analysis.
- Understand numpy arrays and how they differ from python lists
- Create, inspect, reshape and index arrays
- perform vectorized mathematical operations without writing loops
- filter data using boolean conditions

In [2]:
%pip install numpy
# uv add numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.5.3
3.0.6


In [8]:
# python list
numbers = [10, 20, 30, 40]
print(numbers)

print(type(numbers))

[10, 20, 30, 40]
<class 'list'>


In [9]:
# create a numpy array

numbers = np.array([10, 20, 30, 40])
print(numbers)

print(type(numbers))

[10 20 30 40]
<class 'numpy.ndarray'>


### Python list vs. Numpy array

In [10]:
python_list = [10, 20, 30, 40]

numpy_array = np.array([10, 20, 30, 40])

print(python_list * 2)
print(numpy_array * 2)

[10, 20, 30, 40, 10, 20, 30, 40]
[20 40 60 80]


In [11]:
print ("*" * 50)

**************************************************


### Creating Numpy Arrays
- scalar (single number) zero-dimensional 
- one-dimensional (1) - shape (5,)
    - list/vector 
- two-dimensional (2) - shape (3,3), (2,2)
    - matrix/table 
- multi-dimensional arrays (3+) - shape (32, 32, 3)
    - Tensor (eg. color images) 

In [16]:
# 1D-array (a vector)

a = np.array([10, 20, 30, 40])
print(a)
print(a.ndim)
print(a.shape)

[10 20 30 40]
1
(4,)


In [19]:
# 2D-array (a matrix)

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64


In [20]:
arr = np.array([
   [
       [[1, 2, 3], [4, 5, 6]],
       [[7, 8, 9], [10, 11, 12]]
   ],
   [
       [[13, 14, 15], [16, 17, 18]],
       [[19, 20, 21], [22, 23, 24]]
   ]
])

print(arr)
print(arr.shape)
print(arr.ndim)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
(2, 2, 2, 3)
4


In [22]:
# 3D-array (a tensor)

a = np.ones((3, 5, 2))

print(a)
print(a.ndim)
print(a.shape)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
3
(3, 5, 2)


In [23]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [30]:
a = np.ones((5, 5))
print(a.shape)

print(a * 3)

(5, 5)
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [24]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [26]:
a = np.arange(0, 10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
a = np.linspace(0, 1, 5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


### Reshaping arrays

In [42]:
numbers = np.arange(12)

print(numbers)
print ("*" * 50)
print(numbers.reshape(4, -1)) # infer the last column - use -1
# print(numbers.reshape(4, 3))
print ("*" * 50)
print(numbers.reshape(-1,6))
print ("*" * 50)
print(numbers.reshape(6,2))
print ("*" * 50)
print(numbers.reshape(12,1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
**************************************************
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
**************************************************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
**************************************************
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
**************************************************
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


### Vectorized operations

In [43]:
prices = np.array([10, 20, 30, 40])

print(prices + 5)
print(prices * 2)
print(prices / 10)
print(prices ** 2)

[15 25 35 45]
[20 40 60 80]
[1. 2. 3. 4.]
[ 100  400  900 1600]


In [44]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)  # [11 22 33]
print(a * b)  # [10 40 90]

[11 22 33]
[10 40 90]


### Aggregation and Statistics

In [55]:
scores = np.array([70, 85, 90, 65, 100])

print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Standard deviation:", np.std(scores))

Sum: 410
Mean: 82.0
Median: 85.0
Minimum: 65
Maximum: 100
Standard deviation: 12.884098726725126


### Aggregation by axis

In [49]:
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [90, 95, 100]
])

print(scores)

print(np.mean(scores, axis=0)) # collapse the rows, and calculate result for each column

[[ 80  90  70]
 [ 60  75  85]
 [ 90  95 100]]
[76.66666667 86.66666667 85.        ]


In [53]:
print(np.mean(scores, axis=1)) # collapse the columns, and calculate result for each row

[80.         73.33333333 95.        ]


In [54]:
print(np.mean(scores)) # aggregate across all elements by default

82.77777777777777


### Boolean Indexing and filtering
- suppose you want to find every student who score at least 80

In [60]:
scores = np.array([45, 80, 92, 67, 88, 55])

passed = scores >= 80
print(scores[scores >= 80])

print ("*" * 50)
print(passed)
print(scores[passed])

[80 92 88]
**************************************************
[False  True  True False  True False]
[80 92 88]


In [61]:
scores = np.array([45, 60, 75, 80, 90, 100])

print(scores[(scores >= 60) & (scores <= 90)])

[60 75 80 90]


### Indexing and slicing
- numpy uses zero-based indexing, just like python list

In [75]:
numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[-1])
print(numbers[1:4])
print(numbers[1:])
print(numbers[:2])
print(numbers[:])
print(numbers[::2])

10
50
[20 30 40]
[20 30 40 50]
[10 20]
[10 20 30 40 50]
[10 30 50]


### Accessing elements in a 2D array